In [779]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
import itertools

# from sklearn.preprocessing import StandardScaler    # 표준화.
# from sklearn.cluster import KMeans                  # 군집화

import warnings  
warnings.filterwarnings('ignore')

In [725]:
path = 'E:\기업프로젝트\profile_ymti_data_ver2'
path2 = 'E:\기업프로젝트\log_data_1027_2'
df = pd.read_csv(path+'\ymti_data.csv',engine='c',encoding='UTF-8')                                     # 원데이터
df_2030 = pd.read_csv(path + '\ymti_edit_data.csv',engine='c',encoding='UTF-8')                         # 20,30대 YMTI 데이터

want_df = pd.read_csv(path2 + '\want_log.csv',engine='c',encoding='UTF-8')                              # 만나고 싶어요 로그
concn_df = pd.read_csv(path2 + '\concn_log.csv',engine='c',encoding='UTF-8')                            # 관심있어요 로그
msg_df = pd.read_csv(path2 + '\msg_log.csv',engine='c',encoding='UTF-8')                                # 메세지 로그
pf_view_df = pd.read_csv(path2 + '\pf_view_log.csv',engine='c',encoding='UTF-8')                        # 프로필 열람 로그

married_df = pd.read_csv(path2 + '\married_success_sample.csv',engine='c',encoding='UTF-8')             # 결혼 성공 사례 로그

In [726]:
df_2030

,mem_no,mem_sex,mem_age,mem_loc,mem_birth_ddi,mate_blood,pf_ins_yn,mbti_code,food_cat
0,1613793,m,38,d,4,3,y,INFJ,"C,K"
1,1186343,m,38,h,4,3,y,INFP,"J,W,K"
2,1525788,m,25,k,5,3,y,ENFP,"J,C,W,K"
3,1613346,m,37,b,5,2,y,INFP,"W,K"
4,1365388,f,36,i,6,2,y,ESFP,"C,W,K"
...,...,...,...,...,...,...,...,...,...
9335,1680076,f,26,b,4,1,y,INTP,"C,W,K"
9336,1629193,f,27,a,3,3,y,ESFP,"J,C,W,K"
9337,1386307,f,32,b,10,3,y,ENTJ,"K,J,E,D,W"
9338,1680916,m,37,i,5,1,y,ENFP,"J,E,W,K"
9339,1360816,f,27,e,3,1,y,INFP,"D,W,K"

* 만나고 싶어요

In [727]:
want_df

,mem_no,mem_sex,acpt_yn,mem_mbti_code,ptr_mem_no,ptr_mem_sex,ptr_acpt_yn,ptr_mbti_code,open_slct,want_slct,read_yn,ins_date
0,1663087,m,y,ISFP,1666973,f,n,ISFP,f,c,y,2021-09-25 23:38:45
1,1429227,m,y,INFP,1646015,f,n,ENFJ,f,c,n,2021-09-28 22:17:30
2,1414642,m,y,INFP,1619629,f,n,ENFJ,f,c,y,2021-09-28 00:40:55
3,1525643,m,y,ENTP,1619629,f,n,ENFJ,f,s,y,2021-09-10 21:53:33
4,967298,m,y,ESTJ,1661325,f,n,INFP,f,s,n,2021-09-23 20:51:21
...,...,...,...,...,...,...,...,...,...,...,...,...
1242,1670270,m,y,ESFJ,1345654,f,n,ENFJ,f,c,n,2021-09-28 20:58:45
1243,1560654,m,y,INFP,1602829,f,n,ESFP,f,c,y,2021-09-29 16:44:36
1244,799363,f,y,INFJ,1545903,m,n,ISTP,f,s,y,2021-09-24 18:04:10
1245,1288260,m,y,ESFJ,1592728,f,n,ISFP,f,c,n,2021-09-29 22:49:50
1246,1661751,m,y,ENTJ,1667547,f,n,ENFJ,f,c,y,2021-09-25 11:28:21

In [728]:
want_df.mem_mbti_code.unique()

array(['ISFP', 'INFP', 'ENTP', 'ESTJ', 'ESFP', 'ESFJ', 'ENTJ', 'INFJ',
       'ENFP', 'ISFJ', 'INTJ', 'INTP', 'ESTP', 'ENFJ', 'ISTP', 'ISTJ'],
      dtype=object)

In [729]:
# I
want_df1 = dict(want_df[want_df['mem_mbti_code']=="ISTJ"].ptr_mbti_code.value_counts())
want_df2 = dict(want_df[want_df['mem_mbti_code']=="ISTP"].ptr_mbti_code.value_counts())
want_df3 = dict(want_df[want_df['mem_mbti_code']=="ISFJ"].ptr_mbti_code.value_counts())
want_df4 = dict(want_df[want_df['mem_mbti_code']=="ISFP"].ptr_mbti_code.value_counts())
want_df5 = dict(want_df[want_df['mem_mbti_code']=="INFJ"].ptr_mbti_code.value_counts())
want_df6 = dict(want_df[want_df['mem_mbti_code']=="INFP"].ptr_mbti_code.value_counts())
want_df7 = dict(want_df[want_df['mem_mbti_code']=="INTJ"].ptr_mbti_code.value_counts())
want_df8 = dict(want_df[want_df['mem_mbti_code']=="INTP"].ptr_mbti_code.value_counts())
# E
want_df9 = dict(want_df[want_df['mem_mbti_code']=="ESTJ"].ptr_mbti_code.value_counts())
want_df10 = dict(want_df[want_df['mem_mbti_code']=="ESTP"].ptr_mbti_code.value_counts())
want_df11 = dict(want_df[want_df['mem_mbti_code']=="ESFJ"].ptr_mbti_code.value_counts())
want_df12 = dict(want_df[want_df['mem_mbti_code']=="ESFP"].ptr_mbti_code.value_counts())
want_df13 = dict(want_df[want_df['mem_mbti_code']=="ENFJ"].ptr_mbti_code.value_counts())
want_df14 = dict(want_df[want_df['mem_mbti_code']=="ENFP"].ptr_mbti_code.value_counts())
want_df15 = dict(want_df[want_df['mem_mbti_code']=="ENTJ"].ptr_mbti_code.value_counts())
want_df16 = dict(want_df[want_df['mem_mbti_code']=="ENTP"].ptr_mbti_code.value_counts())


want_df1

{'ISFP': 8,
 'INFP': 4,
 'ENFP': 3,
 'INFJ': 3,
 'ENFJ': 2,
 'ESFJ': 2,
 'INTP': 2,
 'ENTJ': 1,
 'ESTJ': 1,
 'ISFJ': 1,
 'ENTP': 1,
 'ESFP': 1,
 'ESTP': 1,
 'ISTP': 1}

In [730]:
want_df1 = pd.DataFrame(want_df1,index =['ISTJ'],columns=['ISFP', 'INFP', 'ENTP', 'ESTJ', 'ESFP', 'ESFJ', 'ENTJ', 'INFJ',
       'ENFP', 'ISFJ', 'INTJ', 'INTP', 'ESTP', 'ENFJ', 'ISTP', 'ISTJ'])
want_df2 = pd.DataFrame(want_df2,index =['ISTP'],columns=['ISFP', 'INFP', 'ENTP', 'ESTJ', 'ESFP', 'ESFJ', 'ENTJ', 'INFJ',
       'ENFP', 'ISFJ', 'INTJ', 'INTP', 'ESTP', 'ENFJ', 'ISTP', 'ISTJ'])
want_df3 = pd.DataFrame(want_df3,index =['ISFJ'],columns=['ISFP', 'INFP', 'ENTP', 'ESTJ', 'ESFP', 'ESFJ', 'ENTJ', 'INFJ',
       'ENFP', 'ISFJ', 'INTJ', 'INTP', 'ESTP', 'ENFJ', 'ISTP', 'ISTJ'])
want_df4 = pd.DataFrame(want_df4,index =['ISFP'],columns=['ISFP', 'INFP', 'ENTP', 'ESTJ', 'ESFP', 'ESFJ', 'ENTJ', 'INFJ',
       'ENFP', 'ISFJ', 'INTJ', 'INTP', 'ESTP', 'ENFJ', 'ISTP', 'ISTJ'])
want_df5 = pd.DataFrame(want_df5,index =['INFJ'],columns=['ISFP', 'INFP', 'ENTP', 'ESTJ', 'ESFP', 'ESFJ', 'ENTJ', 'INFJ',
       'ENFP', 'ISFJ', 'INTJ', 'INTP', 'ESTP', 'ENFJ', 'ISTP', 'ISTJ'])
want_df6 = pd.DataFrame(want_df6,index =['INFP'],columns=['ISFP', 'INFP', 'ENTP', 'ESTJ', 'ESFP', 'ESFJ', 'ENTJ', 'INFJ',
       'ENFP', 'ISFJ', 'INTJ', 'INTP', 'ESTP', 'ENFJ', 'ISTP', 'ISTJ'])
want_df7 = pd.DataFrame(want_df7,index =['INTJ'],columns=['ISFP', 'INFP', 'ENTP', 'ESTJ', 'ESFP', 'ESFJ', 'ENTJ', 'INFJ',
       'ENFP', 'ISFJ', 'INTJ', 'INTP', 'ESTP', 'ENFJ', 'ISTP', 'ISTJ'])
want_df8 = pd.DataFrame(want_df8,index =['INTP'],columns=['ISFP', 'INFP', 'ENTP', 'ESTJ', 'ESFP', 'ESFJ', 'ENTJ', 'INFJ',
       'ENFP', 'ISFJ', 'INTJ', 'INTP', 'ESTP', 'ENFJ', 'ISTP', 'ISTJ'])


want_df9 = pd.DataFrame(want_df9,index =['ESTJ'],columns=['ISFP', 'INFP', 'ENTP', 'ESTJ', 'ESFP', 'ESFJ', 'ENTJ', 'INFJ',
       'ENFP', 'ISFJ', 'INTJ', 'INTP', 'ESTP', 'ENFJ', 'ISTP', 'ISTJ'])
want_df10 = pd.DataFrame(want_df10,index =['ESTP'],columns=['ISFP', 'INFP', 'ENTP', 'ESTJ', 'ESFP', 'ESFJ', 'ENTJ', 'INFJ',
       'ENFP', 'ISFJ', 'INTJ', 'INTP', 'ESTP', 'ENFJ', 'ISTP', 'ISTJ'])
want_df11 = pd.DataFrame(want_df11,index =['ESFJ'],columns=['ISFP', 'INFP', 'ENTP', 'ESTJ', 'ESFP', 'ESFJ', 'ENTJ', 'INFJ',
       'ENFP', 'ISFJ', 'INTJ', 'INTP', 'ESTP', 'ENFJ', 'ISTP', 'ISTJ'])
want_df12 = pd.DataFrame(want_df12,index =['ESFP'],columns=['ISFP', 'INFP', 'ENTP', 'ESTJ', 'ESFP', 'ESFJ', 'ENTJ', 'INFJ',
       'ENFP', 'ISFJ', 'INTJ', 'INTP', 'ESTP', 'ENFJ', 'ISTP', 'ISTJ'])
want_df13 = pd.DataFrame(want_df13,index =['ENFJ'],columns=['ISFP', 'INFP', 'ENTP', 'ESTJ', 'ESFP', 'ESFJ', 'ENTJ', 'INFJ',
       'ENFP', 'ISFJ', 'INTJ', 'INTP', 'ESTP', 'ENFJ', 'ISTP', 'ISTJ'])
want_df14 = pd.DataFrame(want_df14,index =['ENFP'],columns=['ISFP', 'INFP', 'ENTP', 'ESTJ', 'ESFP', 'ESFJ', 'ENTJ', 'INFJ',
       'ENFP', 'ISFJ', 'INTJ', 'INTP', 'ESTP', 'ENFJ', 'ISTP', 'ISTJ'])
want_df15 = pd.DataFrame(want_df15,index =['ENTJ'],columns=['ISFP', 'INFP', 'ENTP', 'ESTJ', 'ESFP', 'ESFJ', 'ENTJ', 'INFJ',
       'ENFP', 'ISFJ', 'INTJ', 'INTP', 'ESTP', 'ENFJ', 'ISTP', 'ISTJ'])
want_df16 = pd.DataFrame(want_df16,index =['ENTP'],columns=['ISFP', 'INFP', 'ENTP', 'ESTJ', 'ESFP', 'ESFJ', 'ENTJ', 'INFJ',
       'ENFP', 'ISFJ', 'INTJ', 'INTP', 'ESTP', 'ENFJ', 'ISTP', 'ISTJ'])

In [731]:
new_want = pd.concat([want_df1,want_df2,want_df3,want_df4,want_df5,want_df6,want_df7,want_df8,want_df9,want_df10,want_df11,want_df12,want_df13,want_df14,want_df15,want_df16])
new_want = new_want.fillna(0)
new_want = new_want.transpose()
new_want

,ISTJ,ISTP,ISFJ,ISFP,INFJ,INFP,INTJ,INTP,ESTJ,ESTP,ESFJ,ESFP,ENFJ,ENFP,ENTJ,ENTP
ISFP,8,4,7,35,13,35,9,5,14,4,10,12,10,19,6,3
INFP,4,13,12,24,15,60,11,8,23,4,4,11,9,25,7,5
ENTP,1,0,1,2,5,9,1,0,1,1,1,4,2,4,0,1
ESTJ,1,1,1,2,4,15,1,0,3,1,2,1,3,3,1,1
ESFP,1,5,3,11,5,19,3,4,5,1,1,5,0,5,0,1
ESFJ,2,1,3,12,4,6,2,3,8,1,1,7,0,6,1,0
ENTJ,1,1,2,2,2,9,2,4,5,0,0,2,0,3,0,1
INFJ,3,1,1,9,3,23,1,6,10,0,5,6,5,11,1,1
ENFP,3,2,4,10,13,21,1,3,8,2,3,5,6,14,1,1
ISFJ,1,6,8,15,8,18,3,6,14,1,4,10,5,5,4,1
INTJ,0,1,2,8,3,5,0,1,2,1,1,1,2,3,1,0
INTP,2,1,1,6,4,15,2,2,5,3,3,2,4,9,4,1
ESTP,1,2,1,2,4,3,0,0,2,1,1,0,1,2,1,1
ENFJ,2,3,2,13,3,22,3,5,13,2,3,3,5,9,3,2
ISTP,1,1,3,7,7,8,0,0,6,0,1,2,2,4,0,2
ISTJ,0,3,1,2,3,8,2,1,5,1,1,5,2,2,1,2

In [732]:
new_want[['ISTJ']].max()

ISTJ    8
dtype: int64

* 관심있어요

In [733]:
concn_df

,mem_no,mem_sex,mem_mbti_code,ptr_mem_no,ptr_mem_sex,ptr_mbti_code,open_slct,ins_date
0,1035596,m,INFJ,1490420,f,ISFJ,n,2021-08-28 08:05:00
1,1035596,m,INFJ,1650613,f,ISFP,n,2021-09-04 18:27:13
2,1035596,m,INFJ,1654611,f,ISTP,n,2021-09-18 07:27:54
3,1575626,m,ENFP,1490420,f,ISFJ,i,2021-09-19 11:41:05
4,1575626,m,ENFP,1668615,f,ENFP,i,2021-10-04 08:46:57
...,...,...,...,...,...,...,...,...
14165,904319,f,ENFP,1202729,m,INFJ,f,2021-10-20 21:12:47
14166,1638077,m,INFP,1687681,f,ISFP,i,2021-10-20 21:13:32
14167,909076,f,ENFP,1292413,m,INFJ,f,2021-10-21 10:49:31
14168,1663346,m,INFP,1684240,f,ENFP,n,2021-10-21 22:57:03
14169,1572093,m,INFP,960047,f,ISFP,f,2021-10-24 00:13:04

In [734]:
# I
concn_df1 = dict(concn_df[concn_df['mem_mbti_code']=="ISTJ"].ptr_mbti_code.value_counts())
concn_df2 = dict(concn_df[concn_df['mem_mbti_code']=="ISTP"].ptr_mbti_code.value_counts())
concn_df3 = dict(concn_df[concn_df['mem_mbti_code']=="ISFJ"].ptr_mbti_code.value_counts())
concn_df4 = dict(concn_df[concn_df['mem_mbti_code']=="ISFP"].ptr_mbti_code.value_counts())
concn_df5 = dict(concn_df[concn_df['mem_mbti_code']=="INFJ"].ptr_mbti_code.value_counts())
concn_df6 = dict(concn_df[concn_df['mem_mbti_code']=="INFP"].ptr_mbti_code.value_counts())
concn_df7 = dict(concn_df[concn_df['mem_mbti_code']=="INTJ"].ptr_mbti_code.value_counts())
concn_df8 = dict(concn_df[concn_df['mem_mbti_code']=="INTP"].ptr_mbti_code.value_counts())
# E
concn_df9 = dict(concn_df[concn_df['mem_mbti_code']=="ESTJ"].ptr_mbti_code.value_counts())
concn_df10 = dict(concn_df[concn_df['mem_mbti_code']=="ESTP"].ptr_mbti_code.value_counts())
concn_df11 = dict(concn_df[concn_df['mem_mbti_code']=="ESFJ"].ptr_mbti_code.value_counts())
concn_df12 = dict(concn_df[concn_df['mem_mbti_code']=="ESFP"].ptr_mbti_code.value_counts())
concn_df13 = dict(concn_df[concn_df['mem_mbti_code']=="ENFJ"].ptr_mbti_code.value_counts())
concn_df14 = dict(concn_df[concn_df['mem_mbti_code']=="ENFP"].ptr_mbti_code.value_counts())
concn_df15 = dict(concn_df[concn_df['mem_mbti_code']=="ENTJ"].ptr_mbti_code.value_counts())
concn_df16 = dict(concn_df[concn_df['mem_mbti_code']=="ENTP"].ptr_mbti_code.value_counts())

# fig = plt.figure(figsize=(30, 20))

# plt.subplot(4, 4, 1)
# concn_cnt = concn_cnt.sort_values(ascending=False)
# concn_cnt.plot.bar(color='green', alpha=0.5)

# plt.subplot(4, 4, 2)
# concn_cnt2 = concn_cnt2.sort_values(ascending=False)
# concn_cnt2.plot.bar(color='green', alpha=0.5)

In [735]:
concn_df1

{'INFP': 32,
 'ISFP': 30,
 'ESFP': 25,
 'ISFJ': 25,
 'INFJ': 24,
 'ENFJ': 20,
 'ESFJ': 17,
 'ENFP': 14,
 'INTP': 13,
 'ESTP': 12,
 'INTJ': 10,
 'ISTP': 10,
 'ISTJ': 8,
 'ENTP': 8,
 'ESTJ': 8,
 'ENTJ': 7}

In [736]:
concn_df1 = pd.DataFrame(concn_df1,index =['ISTJ'],columns=['ISFP', 'INFP', 'ENTP', 'ESTJ', 'ESFP', 'ESFJ', 'ENTJ', 'INFJ',
       'ENFP', 'ISFJ', 'INTJ', 'INTP', 'ESTP', 'ENFJ', 'ISTP', 'ISTJ'])
concn_df2 = pd.DataFrame(concn_df2,index =['ISTP'],columns=['ISFP', 'INFP', 'ENTP', 'ESTJ', 'ESFP', 'ESFJ', 'ENTJ', 'INFJ',
       'ENFP', 'ISFJ', 'INTJ', 'INTP', 'ESTP', 'ENFJ', 'ISTP', 'ISTJ'])
concn_df3 = pd.DataFrame(concn_df3,index =['ISFJ'],columns=['ISFP', 'INFP', 'ENTP', 'ESTJ', 'ESFP', 'ESFJ', 'ENTJ', 'INFJ',
       'ENFP', 'ISFJ', 'INTJ', 'INTP', 'ESTP', 'ENFJ', 'ISTP', 'ISTJ'])
concn_df4 = pd.DataFrame(concn_df4,index =['ISFP'],columns=['ISFP', 'INFP', 'ENTP', 'ESTJ', 'ESFP', 'ESFJ', 'ENTJ', 'INFJ',
       'ENFP', 'ISFJ', 'INTJ', 'INTP', 'ESTP', 'ENFJ', 'ISTP', 'ISTJ'])
concn_df5 = pd.DataFrame(concn_df5,index =['INFJ'],columns=['ISFP', 'INFP', 'ENTP', 'ESTJ', 'ESFP', 'ESFJ', 'ENTJ', 'INFJ',
       'ENFP', 'ISFJ', 'INTJ', 'INTP', 'ESTP', 'ENFJ', 'ISTP', 'ISTJ'])
concn_df6 = pd.DataFrame(concn_df6,index =['INFP'],columns=['ISFP', 'INFP', 'ENTP', 'ESTJ', 'ESFP', 'ESFJ', 'ENTJ', 'INFJ',
       'ENFP', 'ISFJ', 'INTJ', 'INTP', 'ESTP', 'ENFJ', 'ISTP', 'ISTJ'])
concn_df7 = pd.DataFrame(concn_df7,index =['INTJ'],columns=['ISFP', 'INFP', 'ENTP', 'ESTJ', 'ESFP', 'ESFJ', 'ENTJ', 'INFJ',
       'ENFP', 'ISFJ', 'INTJ', 'INTP', 'ESTP', 'ENFJ', 'ISTP', 'ISTJ'])
concn_df8 = pd.DataFrame(concn_df8,index =['INTP'],columns=['ISFP', 'INFP', 'ENTP', 'ESTJ', 'ESFP', 'ESFJ', 'ENTJ', 'INFJ',
       'ENFP', 'ISFJ', 'INTJ', 'INTP', 'ESTP', 'ENFJ', 'ISTP', 'ISTJ'])


concn_df9 = pd.DataFrame(concn_df9,index =['ESTJ'],columns=['ISFP', 'INFP', 'ENTP', 'ESTJ', 'ESFP', 'ESFJ', 'ENTJ', 'INFJ',
       'ENFP', 'ISFJ', 'INTJ', 'INTP', 'ESTP', 'ENFJ', 'ISTP', 'ISTJ'])
concn_df10 = pd.DataFrame(concn_df10,index =['ESTP'],columns=['ISFP', 'INFP', 'ENTP', 'ESTJ', 'ESFP', 'ESFJ', 'ENTJ', 'INFJ',
       'ENFP', 'ISFJ', 'INTJ', 'INTP', 'ESTP', 'ENFJ', 'ISTP', 'ISTJ'])
concn_df11 = pd.DataFrame(concn_df11,index =['ESFJ'],columns=['ISFP', 'INFP', 'ENTP', 'ESTJ', 'ESFP', 'ESFJ', 'ENTJ', 'INFJ',
       'ENFP', 'ISFJ', 'INTJ', 'INTP', 'ESTP', 'ENFJ', 'ISTP', 'ISTJ'])
concn_df12 = pd.DataFrame(concn_df12,index =['ESFP'],columns=['ISFP', 'INFP', 'ENTP', 'ESTJ', 'ESFP', 'ESFJ', 'ENTJ', 'INFJ',
       'ENFP', 'ISFJ', 'INTJ', 'INTP', 'ESTP', 'ENFJ', 'ISTP', 'ISTJ'])
concn_df13 = pd.DataFrame(concn_df13,index =['ENFJ'],columns=['ISFP', 'INFP', 'ENTP', 'ESTJ', 'ESFP', 'ESFJ', 'ENTJ', 'INFJ',
       'ENFP', 'ISFJ', 'INTJ', 'INTP', 'ESTP', 'ENFJ', 'ISTP', 'ISTJ'])
concn_df14 = pd.DataFrame(concn_df14,index =['ENFP'],columns=['ISFP', 'INFP', 'ENTP', 'ESTJ', 'ESFP', 'ESFJ', 'ENTJ', 'INFJ',
       'ENFP', 'ISFJ', 'INTJ', 'INTP', 'ESTP', 'ENFJ', 'ISTP', 'ISTJ'])
concn_df15 = pd.DataFrame(concn_df15,index =['ENTJ'],columns=['ISFP', 'INFP', 'ENTP', 'ESTJ', 'ESFP', 'ESFJ', 'ENTJ', 'INFJ',
       'ENFP', 'ISFJ', 'INTJ', 'INTP', 'ESTP', 'ENFJ', 'ISTP', 'ISTJ'])
concn_df16 = pd.DataFrame(concn_df16,index =['ENTP'],columns=['ISFP', 'INFP', 'ENTP', 'ESTJ', 'ESFP', 'ESFJ', 'ENTJ', 'INFJ',
       'ENFP', 'ISFJ', 'INTJ', 'INTP', 'ESTP', 'ENFJ', 'ISTP', 'ISTJ'])

In [737]:
new_concn = pd.concat([concn_df1,concn_df2,concn_df3,concn_df4,concn_df5,concn_df6,concn_df7,concn_df8,concn_df9,concn_df10,concn_df11,concn_df12,concn_df13,concn_df14,concn_df15,concn_df16])
new_concn = new_concn.fillna(0)
new_concn = new_concn.transpose()
new_concn

,ISTJ,ISTP,ISFJ,ISFP,INFJ,INFP,INTJ,INTP,ESTJ,ESTP,ESFJ,ESFP,ENFJ,ENFP,ENTJ,ENTP
ISFP,30,85,158,327,197,415,62,95,33,30,72,79,163,168,57,50
INFP,32,102,166,367,237,581,96,145,57,24,70,70,191,224,65,64
ENTP,8,13,19,44,29,81,13,14,2,3,13,10,17,26,8,8
ESTJ,8,15,19,36,34,59,9,7,3,6,18,18,20,26,12,2
ESFP,25,50,75,126,101,208,28,66,13,19,54,35,82,87,41,26
ESFJ,17,32,44,109,89,145,20,38,12,20,36,33,52,68,33,21
ENTJ,7,9,28,52,43,88,11,20,5,2,15,14,37,29,10,7
INFJ,24,46,54,166,108,205,26,45,17,16,44,44,79,123,32,21
ENFP,14,48,78,168,134,235,43,60,23,16,53,48,107,91,50,22
ISFJ,25,65,102,190,122,235,37,80,26,13,42,52,88,100,40,27
INTJ,10,18,29,63,26,87,13,13,8,7,11,12,35,32,12,12
INTP,13,31,39,79,73,159,19,42,14,5,28,30,64,70,22,20
ESTP,12,11,21,36,37,60,10,12,5,2,15,8,30,27,7,5
ENFJ,20,32,70,143,95,236,18,51,24,8,39,26,56,95,42,16
ISTP,10,24,44,92,65,121,20,32,12,5,27,23,54,49,15,15
ISTJ,8,12,28,63,36,82,16,20,3,13,27,14,32,40,12,13

* 메세지 로그

In [738]:
msg_df

,mem_no,mem_sex,mem_mbti_code,ptr_mem_no,ptr_mem_sex,ptr_mbti_code,msg_type,ins_date
0,1648522,f,ESFP,1583736,m,ISFJ,1,2021-09-01 00:00:10
1,1648522,f,ESFP,1583736,m,ISFJ,1,2021-09-01 00:00:22
2,1648522,f,ESFP,1583736,m,ISFJ,1,2021-09-01 00:00:30
3,1648522,f,ESFP,1583736,m,ISFJ,1,2021-09-01 00:00:53
4,1648522,f,ESFP,1583736,m,ISFJ,1,2021-09-01 00:02:50
...,...,...,...,...,...,...,...,...
455715,1671234,m,INFP,1426225,f,INFP,1,2021-09-29 22:53:50
455716,155715,m,ISFP,1513715,f,INFJ,1,2021-09-29 22:11:25
455717,1671422,f,ENFP,1671468,m,INFJ,1,2021-09-30 02:23:01
455718,1360816,f,INFP,1282906,m,ESTP,1,2021-09-30 00:01:02
455719,1360816,f,INFP,438558,m,ENFJ,1,2021-09-30 01:29:13

In [739]:
msg_df1 = dict(msg_df[msg_df['mem_mbti_code']=="ISTJ"].ptr_mbti_code.value_counts())
msg_df2 = dict(msg_df[msg_df['mem_mbti_code']=="ISTP"].ptr_mbti_code.value_counts())
msg_df3 = dict(msg_df[msg_df['mem_mbti_code']=="ISFJ"].ptr_mbti_code.value_counts())
msg_df4 = dict(msg_df[msg_df['mem_mbti_code']=="ISFP"].ptr_mbti_code.value_counts())
msg_df5 = dict(msg_df[msg_df['mem_mbti_code']=="INFJ"].ptr_mbti_code.value_counts())
msg_df6 = dict(msg_df[msg_df['mem_mbti_code']=="INFP"].ptr_mbti_code.value_counts())
msg_df7 = dict(msg_df[msg_df['mem_mbti_code']=="INTJ"].ptr_mbti_code.value_counts())
msg_df8 = dict(msg_df[msg_df['mem_mbti_code']=="INTP"].ptr_mbti_code.value_counts())

msg_df9 = dict(msg_df[msg_df['mem_mbti_code']=="ESTJ"].ptr_mbti_code.value_counts())
msg_df10 = dict(msg_df[msg_df['mem_mbti_code']=="ESTP"].ptr_mbti_code.value_counts())
msg_df11 = dict(msg_df[msg_df['mem_mbti_code']=="ESFJ"].ptr_mbti_code.value_counts())
msg_df12 = dict(msg_df[msg_df['mem_mbti_code']=="ESFP"].ptr_mbti_code.value_counts())
msg_df13 = dict(msg_df[msg_df['mem_mbti_code']=="ENFJ"].ptr_mbti_code.value_counts())
msg_df14 = dict(msg_df[msg_df['mem_mbti_code']=="ENFP"].ptr_mbti_code.value_counts())
msg_df15 = dict(msg_df[msg_df['mem_mbti_code']=="ENTJ"].ptr_mbti_code.value_counts())
msg_df16 = dict(msg_df[msg_df['mem_mbti_code']=="ENTP"].ptr_mbti_code.value_counts())

msg_df1

{'INFP': 3203,
 'ISFP': 1693,
 'ENFP': 1658,
 'INFJ': 1127,
 'ISFJ': 1005,
 'ENFJ': 935,
 'ESFP': 848,
 'ESFJ': 837,
 'ISTJ': 542,
 'INTJ': 524,
 'INTP': 477,
 'ENTP': 462,
 'ESTJ': 336,
 'ISTP': 293,
 'ESTP': 230,
 'ENTJ': 179}

In [740]:
msg_df1 = pd.DataFrame(msg_df1,index =['ISTJ'],columns=['ISFP', 'INFP', 'ENTP', 'ESTJ', 'ESFP', 'ESFJ', 'ENTJ', 'INFJ',
       'ENFP', 'ISFJ', 'INTJ', 'INTP', 'ESTP', 'ENFJ', 'ISTP', 'ISTJ'])
msg_df2 = pd.DataFrame(msg_df2,index =['ISTP'],columns=['ISFP', 'INFP', 'ENTP', 'ESTJ', 'ESFP', 'ESFJ', 'ENTJ', 'INFJ',
       'ENFP', 'ISFJ', 'INTJ', 'INTP', 'ESTP', 'ENFJ', 'ISTP', 'ISTJ'])
msg_df3 = pd.DataFrame(msg_df3,index =['ISFJ'],columns=['ISFP', 'INFP', 'ENTP', 'ESTJ', 'ESFP', 'ESFJ', 'ENTJ', 'INFJ',
       'ENFP', 'ISFJ', 'INTJ', 'INTP', 'ESTP', 'ENFJ', 'ISTP', 'ISTJ'])
msg_df4 = pd.DataFrame(msg_df4,index =['ISFP'],columns=['ISFP', 'INFP', 'ENTP', 'ESTJ', 'ESFP', 'ESFJ', 'ENTJ', 'INFJ',
       'ENFP', 'ISFJ', 'INTJ', 'INTP', 'ESTP', 'ENFJ', 'ISTP', 'ISTJ'])
msg_df5 = pd.DataFrame(msg_df5,index =['INFJ'],columns=['ISFP', 'INFP', 'ENTP', 'ESTJ', 'ESFP', 'ESFJ', 'ENTJ', 'INFJ',
       'ENFP', 'ISFJ', 'INTJ', 'INTP', 'ESTP', 'ENFJ', 'ISTP', 'ISTJ'])
msg_df6 = pd.DataFrame(msg_df6,index =['INFP'],columns=['ISFP', 'INFP', 'ENTP', 'ESTJ', 'ESFP', 'ESFJ', 'ENTJ', 'INFJ',
       'ENFP', 'ISFJ', 'INTJ', 'INTP', 'ESTP', 'ENFJ', 'ISTP', 'ISTJ'])
msg_df7 = pd.DataFrame(msg_df7,index =['INTJ'],columns=['ISFP', 'INFP', 'ENTP', 'ESTJ', 'ESFP', 'ESFJ', 'ENTJ', 'INFJ',
       'ENFP', 'ISFJ', 'INTJ', 'INTP', 'ESTP', 'ENFJ', 'ISTP', 'ISTJ'])
msg_df8 = pd.DataFrame(msg_df8,index =['INTP'],columns=['ISFP', 'INFP', 'ENTP', 'ESTJ', 'ESFP', 'ESFJ', 'ENTJ', 'INFJ',
       'ENFP', 'ISFJ', 'INTJ', 'INTP', 'ESTP', 'ENFJ', 'ISTP', 'ISTJ'])


msg_df9 = pd.DataFrame(msg_df9,index =['ESTJ'],columns=['ISFP', 'INFP', 'ENTP', 'ESTJ', 'ESFP', 'ESFJ', 'ENTJ', 'INFJ',
       'ENFP', 'ISFJ', 'INTJ', 'INTP', 'ESTP', 'ENFJ', 'ISTP', 'ISTJ'])
msg_df10 = pd.DataFrame(msg_df10,index =['ESTP'],columns=['ISFP', 'INFP', 'ENTP', 'ESTJ', 'ESFP', 'ESFJ', 'ENTJ', 'INFJ',
       'ENFP', 'ISFJ', 'INTJ', 'INTP', 'ESTP', 'ENFJ', 'ISTP', 'ISTJ'])
msg_df11 = pd.DataFrame(msg_df11,index =['ESFJ'],columns=['ISFP', 'INFP', 'ENTP', 'ESTJ', 'ESFP', 'ESFJ', 'ENTJ', 'INFJ',
       'ENFP', 'ISFJ', 'INTJ', 'INTP', 'ESTP', 'ENFJ', 'ISTP', 'ISTJ'])
msg_df12 = pd.DataFrame(msg_df12,index =['ESFP'],columns=['ISFP', 'INFP', 'ENTP', 'ESTJ', 'ESFP', 'ESFJ', 'ENTJ', 'INFJ',
       'ENFP', 'ISFJ', 'INTJ', 'INTP', 'ESTP', 'ENFJ', 'ISTP', 'ISTJ'])
msg_df13 = pd.DataFrame(msg_df13,index =['ENFJ'],columns=['ISFP', 'INFP', 'ENTP', 'ESTJ', 'ESFP', 'ESFJ', 'ENTJ', 'INFJ',
       'ENFP', 'ISFJ', 'INTJ', 'INTP', 'ESTP', 'ENFJ', 'ISTP', 'ISTJ'])
msg_df14 = pd.DataFrame(msg_df14,index =['ENFP'],columns=['ISFP', 'INFP', 'ENTP', 'ESTJ', 'ESFP', 'ESFJ', 'ENTJ', 'INFJ',
       'ENFP', 'ISFJ', 'INTJ', 'INTP', 'ESTP', 'ENFJ', 'ISTP', 'ISTJ'])
msg_df15 = pd.DataFrame(msg_df15,index =['ENTJ'],columns=['ISFP', 'INFP', 'ENTP', 'ESTJ', 'ESFP', 'ESFJ', 'ENTJ', 'INFJ',
       'ENFP', 'ISFJ', 'INTJ', 'INTP', 'ESTP', 'ENFJ', 'ISTP', 'ISTJ'])
msg_df16 = pd.DataFrame(msg_df16,index =['ENTP'],columns=['ISFP', 'INFP', 'ENTP', 'ESTJ', 'ESFP', 'ESFJ', 'ENTJ', 'INFJ',
       'ENFP', 'ISFJ', 'INTJ', 'INTP', 'ESTP', 'ENFJ', 'ISTP', 'ISTJ'])

In [741]:
new_msg = pd.concat([msg_df1,msg_df2,msg_df3,msg_df4,msg_df5,msg_df6,msg_df7,msg_df8,msg_df9,msg_df10,msg_df11,msg_df12,msg_df13,msg_df14,msg_df15,msg_df16])
new_msg = new_msg.fillna(0)
new_msg = new_msg.transpose()
new_msg

,ISTJ,ISTP,ISFJ,ISFP,INFJ,INFP,INTJ,INTP,ESTJ,ESTP,ESFJ,ESFP,ENFJ,ENFP,ENTJ,ENTP
ISFP,1693,2420,4448,6376,7576,13617,1783,3353,1416,853,2855,2036,4951,5421,1174,2355
INFP,3203,3293,6917,10276,7434,16981,2747,4530,1826,1294,4010,2607,7555,7912,1824,2116
ENTP,462,814,874,1922,1068,2393,439,498,382,184,639,458,1809,813,249,403
ESTJ,336,369,948,1111,1106,1959,210,483,110,218,349,344,801,1210,195,475
ESFP,848,1071,2267,2310,3506,4413,916,1275,432,259,1268,822,2362,2302,782,684
ESFJ,837,535,1687,2716,2138,4606,704,1408,380,261,969,1101,1987,1532,478,766
ENTJ,179,454,1139,996,935,2038,455,433,178,118,413,683,1240,1301,1041,322
INFJ,1127,1286,2875,5609,3483,6622,1009,1993,924,593,1414,2457,2435,2818,687,840
ENFP,1658,1445,3329,4596,3790,8669,2046,1974,1146,347,1553,1641,3046,2592,1366,825
ISFJ,1005,1491,3758,3896,3542,7812,1020,1866,877,820,1698,1780,2760,3253,1294,925
INTJ,524,496,1071,1577,1185,3052,527,451,240,104,461,590,1223,1784,504,452
INTP,477,1069,1631,2773,2355,4979,393,1150,426,558,1252,950,1536,1961,408,544
ESTP,230,409,959,907,961,1814,181,744,290,82,339,294,721,480,201,196
ENFJ,935,916,2284,3617,2744,7242,1119,1433,683,466,1629,1937,2104,2693,1219,1996
ISTP,293,859,1543,2198,1763,3839,532,1130,371,323,634,1029,1372,1360,578,908
ISTJ,542,311,916,1615,1405,3349,504,486,311,177,777,602,1139,1680,188,436

* 프로필 열람 로그

In [742]:
pf_view_df

,mem_no,mem_sex,mem_mbti_code,ptr_mem_no,ptr_mem_sex,ptr_mbti_code,open_type,open_date
0,1604615,m,INFP,1646817,f,ENFJ,0,2021-09-01 00:00:00
1,1328139,m,ISTP,1646817,f,ENFJ,0,2021-09-23 00:05:46
2,1314528,m,ENFP,1646817,f,ENFJ,0,2021-09-02 13:58:41
3,992443,m,ISFJ,1646817,f,ENFJ,0,2021-09-03 11:39:13
4,992443,m,ISFJ,1646817,f,ENFJ,0,2021-09-05 10:44:53
...,...,...,...,...,...,...,...,...
1859507,1686164,f,INFP,1076051,m,INFJ,0,2021-10-20 20:39:22
1859508,1687693,f,ISFP,1285085,m,INFJ,0,2021-10-21 17:41:54
1859509,1687693,f,ISFP,1285085,m,INFJ,0,2021-10-21 17:41:55
1859510,1687693,f,ISFP,503528,m,ISFJ,0,2021-10-22 00:16:02
1859511,1687693,f,ISFP,503528,m,ISFJ,0,2021-10-22 00:16:04

In [743]:
pf_view_df1 = dict(pf_view_df[pf_view_df['mem_mbti_code']=="ISTJ"].ptr_mbti_code.value_counts())
pf_view_df2 = dict(pf_view_df[pf_view_df['mem_mbti_code']=="ISTP"].ptr_mbti_code.value_counts())
pf_view_df3 = dict(pf_view_df[pf_view_df['mem_mbti_code']=="ISFJ"].ptr_mbti_code.value_counts())
pf_view_df4 = dict(pf_view_df[pf_view_df['mem_mbti_code']=="ISFP"].ptr_mbti_code.value_counts())
pf_view_df5 = dict(pf_view_df[pf_view_df['mem_mbti_code']=="INFJ"].ptr_mbti_code.value_counts())
pf_view_df6 = dict(pf_view_df[pf_view_df['mem_mbti_code']=="INFP"].ptr_mbti_code.value_counts())
pf_view_df7 = dict(pf_view_df[pf_view_df['mem_mbti_code']=="INTJ"].ptr_mbti_code.value_counts())
pf_view_df8 = dict(pf_view_df[pf_view_df['mem_mbti_code']=="INTP"].ptr_mbti_code.value_counts())

pf_view_df9 = dict(pf_view_df[pf_view_df['mem_mbti_code']=="ESTJ"].ptr_mbti_code.value_counts())
pf_view_df10 = dict(pf_view_df[pf_view_df['mem_mbti_code']=="ESTP"].ptr_mbti_code.value_counts())
pf_view_df11 = dict(pf_view_df[pf_view_df['mem_mbti_code']=="ESFJ"].ptr_mbti_code.value_counts())
pf_view_df12 = dict(pf_view_df[pf_view_df['mem_mbti_code']=="ESFP"].ptr_mbti_code.value_counts())
pf_view_df13 = dict(pf_view_df[pf_view_df['mem_mbti_code']=="ENFJ"].ptr_mbti_code.value_counts())
pf_view_df14 = dict(pf_view_df[pf_view_df['mem_mbti_code']=="ENFP"].ptr_mbti_code.value_counts())
pf_view_df15 = dict(pf_view_df[pf_view_df['mem_mbti_code']=="ENTJ"].ptr_mbti_code.value_counts())
pf_view_df16 = dict(pf_view_df[pf_view_df['mem_mbti_code']=="ENTP"].ptr_mbti_code.value_counts())

pf_view_df1

{'INFP': 9020,
 'ISFP': 7084,
 'INFJ': 4128,
 'ISFJ': 4074,
 'ENFP': 4032,
 'ENFJ': 3721,
 'ESFP': 3170,
 'INTP': 2477,
 'ESFJ': 2438,
 'ISTP': 2154,
 'ISTJ': 1727,
 'ENTP': 1244,
 'INTJ': 1243,
 'ENTJ': 1242,
 'ESTP': 1091,
 'ESTJ': 963}

In [744]:
pf_view_df1 = pd.DataFrame(pf_view_df1,index =['ISTJ'],columns=['ISFP', 'INFP', 'ENTP', 'ESTJ', 'ESFP', 'ESFJ', 'ENTJ', 'INFJ',
       'ENFP', 'ISFJ', 'INTJ', 'INTP', 'ESTP', 'ENFJ', 'ISTP', 'ISTJ'])
pf_view_df2 = pd.DataFrame(pf_view_df2,index =['ISTP'],columns=['ISFP', 'INFP', 'ENTP', 'ESTJ', 'ESFP', 'ESFJ', 'ENTJ', 'INFJ',
       'ENFP', 'ISFJ', 'INTJ', 'INTP', 'ESTP', 'ENFJ', 'ISTP', 'ISTJ'])
pf_view_df3 = pd.DataFrame(pf_view_df3,index =['ISFJ'],columns=['ISFP', 'INFP', 'ENTP', 'ESTJ', 'ESFP', 'ESFJ', 'ENTJ', 'INFJ',
       'ENFP', 'ISFJ', 'INTJ', 'INTP', 'ESTP', 'ENFJ', 'ISTP', 'ISTJ'])
pf_view_df4 = pd.DataFrame(pf_view_df4,index =['ISFP'],columns=['ISFP', 'INFP', 'ENTP', 'ESTJ', 'ESFP', 'ESFJ', 'ENTJ', 'INFJ',
       'ENFP', 'ISFJ', 'INTJ', 'INTP', 'ESTP', 'ENFJ', 'ISTP', 'ISTJ'])
pf_view_df5 = pd.DataFrame(pf_view_df5,index =['INFJ'],columns=['ISFP', 'INFP', 'ENTP', 'ESTJ', 'ESFP', 'ESFJ', 'ENTJ', 'INFJ',
       'ENFP', 'ISFJ', 'INTJ', 'INTP', 'ESTP', 'ENFJ', 'ISTP', 'ISTJ'])
pf_view_df6 = pd.DataFrame(pf_view_df6,index =['INFP'],columns=['ISFP', 'INFP', 'ENTP', 'ESTJ', 'ESFP', 'ESFJ', 'ENTJ', 'INFJ',
       'ENFP', 'ISFJ', 'INTJ', 'INTP', 'ESTP', 'ENFJ', 'ISTP', 'ISTJ'])
pf_view_df7 = pd.DataFrame(pf_view_df7,index =['INTJ'],columns=['ISFP', 'INFP', 'ENTP', 'ESTJ', 'ESFP', 'ESFJ', 'ENTJ', 'INFJ',
       'ENFP', 'ISFJ', 'INTJ', 'INTP', 'ESTP', 'ENFJ', 'ISTP', 'ISTJ'])
pf_view_df8 = pd.DataFrame(pf_view_df8,index =['INTP'],columns=['ISFP', 'INFP', 'ENTP', 'ESTJ', 'ESFP', 'ESFJ', 'ENTJ', 'INFJ',
       'ENFP', 'ISFJ', 'INTJ', 'INTP', 'ESTP', 'ENFJ', 'ISTP', 'ISTJ'])


pf_view_df9 = pd.DataFrame(pf_view_df9,index =['ESTJ'],columns=['ISFP', 'INFP', 'ENTP', 'ESTJ', 'ESFP', 'ESFJ', 'ENTJ', 'INFJ',
       'ENFP', 'ISFJ', 'INTJ', 'INTP', 'ESTP', 'ENFJ', 'ISTP', 'ISTJ'])
pf_view_df10 = pd.DataFrame(pf_view_df10,index =['ESTP'],columns=['ISFP', 'INFP', 'ENTP', 'ESTJ', 'ESFP', 'ESFJ', 'ENTJ', 'INFJ',
       'ENFP', 'ISFJ', 'INTJ', 'INTP', 'ESTP', 'ENFJ', 'ISTP', 'ISTJ'])
pf_view_df11 = pd.DataFrame(pf_view_df11,index =['ESFJ'],columns=['ISFP', 'INFP', 'ENTP', 'ESTJ', 'ESFP', 'ESFJ', 'ENTJ', 'INFJ',
       'ENFP', 'ISFJ', 'INTJ', 'INTP', 'ESTP', 'ENFJ', 'ISTP', 'ISTJ'])
pf_view_df12 = pd.DataFrame(pf_view_df12,index =['ESFP'],columns=['ISFP', 'INFP', 'ENTP', 'ESTJ', 'ESFP', 'ESFJ', 'ENTJ', 'INFJ',
       'ENFP', 'ISFJ', 'INTJ', 'INTP', 'ESTP', 'ENFJ', 'ISTP', 'ISTJ'])
pf_view_df13 = pd.DataFrame(pf_view_df13,index =['ENFJ'],columns=['ISFP', 'INFP', 'ENTP', 'ESTJ', 'ESFP', 'ESFJ', 'ENTJ', 'INFJ',
       'ENFP', 'ISFJ', 'INTJ', 'INTP', 'ESTP', 'ENFJ', 'ISTP', 'ISTJ'])
pf_view_df14 = pd.DataFrame(pf_view_df14,index =['ENFP'],columns=['ISFP', 'INFP', 'ENTP', 'ESTJ', 'ESFP', 'ESFJ', 'ENTJ', 'INFJ',
       'ENFP', 'ISFJ', 'INTJ', 'INTP', 'ESTP', 'ENFJ', 'ISTP', 'ISTJ'])
pf_view_df15 = pd.DataFrame(pf_view_df15,index =['ENTJ'],columns=['ISFP', 'INFP', 'ENTP', 'ESTJ', 'ESFP', 'ESFJ', 'ENTJ', 'INFJ',
       'ENFP', 'ISFJ', 'INTJ', 'INTP', 'ESTP', 'ENFJ', 'ISTP', 'ISTJ'])
pf_view_df16 = pd.DataFrame(pf_view_df16,index =['ENTP'],columns=['ISFP', 'INFP', 'ENTP', 'ESTJ', 'ESFP', 'ESFJ', 'ENTJ', 'INFJ',
       'ENFP', 'ISFJ', 'INTJ', 'INTP', 'ESTP', 'ENFJ', 'ISTP', 'ISTJ'])

In [745]:
new_pf = pd.concat([pf_view_df1,pf_view_df2,pf_view_df3,pf_view_df4,pf_view_df5,pf_view_df6,pf_view_df7,pf_view_df8,pf_view_df9,pf_view_df10,pf_view_df11,pf_view_df12,pf_view_df13,pf_view_df14,pf_view_df15,pf_view_df16])
new_pf = new_pf.fillna(0)
new_pf = new_pf.transpose()
new_pf

,ISTJ,ISTP,ISFJ,ISFP,INFJ,INFP,INTJ,INTP,ESTJ,ESTP,ESFJ,ESFP,ENFJ,ENFP,ENTJ,ENTP
ISFP,7084,12919,19424,35301,27568,59663,7429,13951,4020,3652,10076,11478,16941,19941,4958,7164
INFP,9020,17725,25286,48428,34235,81482,10148,19169,5468,5089,12501,16500,23086,27799,7139,10361
ENTP,1244,2424,3621,6664,5160,11256,1508,2586,755,674,1842,2202,3161,3935,963,1474
ESTJ,963,1821,2878,5167,3766,7450,1043,1723,556,510,1434,1732,2639,2677,733,893
ESFP,3170,5895,9729,15658,13346,26709,3291,6246,1753,1627,4544,5254,8316,9194,2301,3223
ESFJ,2438,4375,7154,12884,9756,19303,2490,4386,1332,1332,3848,4117,6342,6933,1839,2412
ENTJ,1242,2249,3620,6057,4906,10807,1294,2642,699,647,1925,2143,3253,3712,1015,1311
INFJ,4128,7210,11419,20345,14662,31631,4035,7827,2448,2316,5751,7409,9348,12344,2923,4036
ENFP,4032,7622,11083,20359,16650,34648,4352,8238,2180,2148,5554,6874,9721,11965,3155,4261
ISFJ,4074,7471,11992,20196,15500,31951,4242,7153,2263,2298,6044,7547,9973,11300,3146,3874
INTJ,1243,2199,3742,6516,4593,10793,1566,2504,754,723,1750,2303,3074,3824,1001,1367
INTP,2477,4677,7155,13167,10120,22057,2751,5336,1453,1412,3583,4718,6568,7691,2088,2754
ESTP,1091,1730,2990,4634,4117,7559,995,1829,533,505,1444,1515,2589,2721,719,947
ENFJ,3721,5940,9744,16846,12701,28642,3460,6379,2005,1872,5151,5713,8679,9565,2782,3290
ISTP,2154,4118,6476,11109,8008,18108,2161,4227,1317,1142,3062,3719,5095,6072,1642,2199
ISTJ,1727,2989,4755,8804,6411,13286,1580,2947,950,913,2412,2999,4159,4791,1271,1666

* 모든 로그 MBTI합
    - column이 ISTJ일 때의 row값 확인

In [746]:
new_df = new_concn + new_msg + new_pf + new_want
new_df

,ISTJ,ISTP,ISFJ,ISFP,INFJ,INFP,INTJ,INTP,ESTJ,ESTP,ESFJ,ESFP,ENFJ,ENFP,ENTJ,ENTP
ISFP,8815,15428,24037,42039,35354,73730,9283,17404,5483,4539,13013,13605,22065,25549,6195,9572
INFP,12259,21133,32381,59095,41921,99104,13002,23852,7374,6411,16585,19188,30841,35960,9035,12546
ENTP,1715,3251,4515,8632,6262,13739,1961,3098,1140,862,2495,2674,4989,4778,1220,1886
ESTJ,1308,2206,3846,6316,4910,9483,1263,2213,672,735,1803,2095,3463,3916,941,1371
ESFP,4044,7021,12074,18105,16958,31349,4238,7591,2203,1906,5867,6116,10760,11588,3124,3934
ESFJ,3294,4943,8888,15721,11987,24060,3216,5835,1732,1614,4854,5258,8381,8539,2351,3199
ENTJ,1429,2713,4789,7107,5886,12942,1762,3099,887,767,2353,2842,4530,5045,2066,1641
INFJ,5282,8543,14349,26129,18256,38481,5071,9871,3399,2925,7214,9916,11867,15296,3643,4898
ENFP,5707,9117,14494,25133,20587,43573,6442,10275,3357,2513,7163,8568,12880,14662,4572,5109
ISFJ,5105,9033,15860,24297,19172,40016,5302,9105,3180,3132,7788,9389,12826,14658,4484,4827
INTJ,1777,2714,4844,8164,5807,13937,2106,2969,1004,835,2223,2906,4334,5643,1518,1831
INTP,2969,5778,8826,16025,12552,27210,3165,6530,1898,1978,4866,5700,8172,9731,2522,3319
ESTP,1334,2152,3971,5579,5119,9436,1186,2585,830,590,1799,1817,3341,3230,928,1149
ENFJ,4678,6891,12100,20619,15543,36142,4600,7868,2725,2348,6822,7679,10844,12362,4046,5304
ISTP,2458,5002,8066,13406,9843,22076,2713,5389,1706,1470,3724,4773,6523,7485,2235,3124
ISTJ,2277,3315,5700,10484,7855,16725,2102,3454,1269,1104,3217,3620,5332,6513,1472,2117

In [747]:
new_df.index

Index(['ISFP', 'INFP', 'ENTP', 'ESTJ', 'ESFP', 'ESFJ', 'ENTJ', 'INFJ', 'ENFP',
       'ISFJ', 'INTJ', 'INTP', 'ESTP', 'ENFJ', 'ISTP', 'ISTJ'],
      dtype='object')

In [748]:
new_df.columns

Index(['ISTJ', 'ISTP', 'ISFJ', 'ISFP', 'INFJ', 'INFP', 'INTJ', 'INTP', 'ESTJ',
       'ESTP', 'ESFJ', 'ESFP', 'ENFJ', 'ENFP', 'ENTJ', 'ENTP'],
      dtype='object')

In [755]:
m_list = []
m_list2 = []
for i in range(len(mbti_list)):
    m_list.append(list(new_df[mbti_list[i]].sort_values(ascending=False).index))

for i in range(len(m_list)):
    m_list2.append(m_list[i][:4])
m_list2

[['INFP', 'ISFP', 'ENFP', 'INFJ'],
 ['INFP', 'ISFP', 'ENFP', 'ISFJ'],
 ['INFP', 'ISFP', 'ISFJ', 'ENFP'],
 ['INFP', 'ISFP', 'INFJ', 'ENFP'],
 ['INFP', 'ISFP', 'ENFP', 'ISFJ'],
 ['INFP', 'ISFP', 'ENFP', 'ISFJ'],
 ['INFP', 'ISFP', 'ENFP', 'ISFJ'],
 ['INFP', 'ISFP', 'ENFP', 'INFJ'],
 ['INFP', 'ISFP', 'INFJ', 'ENFP'],
 ['INFP', 'ISFP', 'ISFJ', 'INFJ'],
 ['INFP', 'ISFP', 'ISFJ', 'INFJ'],
 ['INFP', 'ISFP', 'INFJ', 'ISFJ'],
 ['INFP', 'ISFP', 'ENFP', 'ISFJ'],
 ['INFP', 'ISFP', 'INFJ', 'ENFP'],
 ['INFP', 'ISFP', 'ENFP', 'ISFJ'],
 ['INFP', 'ISFP', 'ENFJ', 'ENFP']]

* 1순위 MBTI 분류

In [785]:
new_df.idxmax()
df_1 = pd.DataFrame(index=new_df.columns,columns=['1st'],data=new_df.idxmax())
df_2 = pd.DataFrame(index=new_df.columns,columns=['2nd'],data='ISFP')
# df_3 = pd.DataFrame(index=new_df.columns,columns=['3st'],data='ISFP')
pd.concat([df_1,df_2],axis=1)

       1st   2nd
ISTJ  INFP  ISFP
ISTP  INFP  ISFP
ISFJ  INFP  ISFP
ISFP  INFP  ISFP
INFJ  INFP  ISFP
INFP  INFP  ISFP
INTJ  INFP  ISFP
INTP  INFP  ISFP
ESTJ  INFP  ISFP
ESTP  INFP  ISFP
ESFJ  INFP  ISFP
ESFP  INFP  ISFP
ENFJ  INFP  ISFP
ENFP  INFP  ISFP
ENTJ  INFP  ISFP
ENTP  INFP  ISFP

* 결혼 성공 사례 로그

In [751]:
# married_df.columns

In [752]:
# married_df

In [753]:
# # df_edit = df.drop(['Unnamed: 0'],axis=1)

# married_df_edit = pd.merge(df_edit, married_df, on = 'mem_no', how = 'inner')
# married_df_edit

In [754]:
# married_df_edit = pd.merge(married_df_edit, want_df, on = 'ptr_mem_no', how = 'inner')
# married_df_edit